### ISSUE TITLE
Migrating from jrk to jrk g2

### ISSUE THREAD

**Issue by sbrian26** [pololu/pololu-jrk-g2-software#1]
We're migrating from a jrk 12v12 to a jrk g2 24v13
Our previous control system ran on windows and utilized the USBWrapper application along with the jrk sdk to send commands and monitor status and feedback etc. 

Come to find out the jrk g2 does not appear to support the USB wrapper command facilities as the generation 1 jrk did. 

What then would you say is the best tac to take (resulting in minimal effort to refactor away from the USBWrapper) to migrate our control systems running in a dotnet development environment?

**Comment by DavidEGrayson** [comment]
Please refer to the "Writing PC Software to control the Jrk" section of the [Jrk G2 user's guide](https://www.pololu.com/docs/0J73/) for the recommended ways of controlling the Jrk G2.

What methods of the Jrk class in the Pololu USB SDK are you using?  If you are just using a few, it might be easy to edit the SDK to support the Jrk G2.

**Comment by sbrian26** [comment]
re: USB SDK- We are using to set position and monitor feedback position and other variables, 

I modified the library to find the g2 (umc05a) but any command attempts to call into the jrk device using the usbwrapper fail e.g. ... ....getVariables().scaledFeedback --- exception: "**Control transfer failed.**" - at Pololu.WinusbHelper.WinUsbDevice.controlTransfer(WINUSB_SETUP_PACKET setupPacket, Void* buffer) 

Is it possible to modify the WinUSBhelper to work with g2? If not, would you suggest modifying it to utilize serial port commands? -- or ??

**Comment by sbrian26** [comment]
> What methods of the Jrk class in the Pololu USB SDK are you using?  If you are just using a few, it might be easy to edit the SDK to support the Jrk G2.

We are using to set position and monitor feedback position and other variables,
I modified the library to find the g2 (umc05a) but any command attempts to call into the jrk device using the usbwrapper fail e.g. ... ....getVariables().scaledFeedback --- **exception: "Control transfer failed."** - at Pololu.WinusbHelper.WinUsbDevice.controlTransfer(WINUSB_SETUP_PACKET setupPacket, Void* buffer)
Is it possible to modify the WinUSBhelper to work with g2? If not, would you suggest modifying it to utilize serial port commands? -- or ?? Just looking for the slimmest path as our control system is based on the jrk.cs interface.

**Comment by DavidEGrayson** [comment]
I think you are referring to the "Set target" command.  That should work fine with no modification.

The "Get variables" command of the Jrk G2 is different from its counterpart on the original Jrks.  You can refer to the documentation of that command in the "Command reference" and "USB command encoding" sections of the [user's guide](https://www.pololu.com/docs/0J73) in order to understand how to modify the code.

If you send an unrecognized control transfer to the Jrk, you get a "Control transfer failed." error.

**Comment by DavidEGrayson** [comment]
Also, I just added information about the Pololu USB SDK to the "Writing PC software to control the Jrk" section of the [user's guide](https://www.pololu.com/docs/0J73/).

**Comment by sbrian26** [comment]
Ok, yes, ("Set target") I jumped to conclusion that all commands were failing, I'll dig into the G2 commands and attempt to modify the USB SDK for what we specifically need, this information is encouraging. Thanks!
